fix: allow generating no sourcemaps
aspect-build/rules_esbuild pull request #93
Opened 2022-11-04 03:32 UTC by jbedard

Fixes #86

2022-11-08 14:10 UTC, mattem requested changes

2022-11-08 14:10 UTC, mattem commented on esbuild/private/esbuild.bzl
> +        default = "linked",
I'm not sure how this was tested, but `None` is defaulted to `linked`, so you can never pass `None` here, so the `fail` line on 240 will always trigger.
We could detect if `False` is passed and set this to a magic string so the API is cleaner, or just have users set the string `"None"` or `"disabled"` etc?

2022-11-08 21:03 UTC, jbedard commented on esbuild/private/esbuild.bzl
> +        default = "linked",
Or default to nothing (empty string?) and let the macro do the default of "linked"? See the latest commit

2022-11-16 11:58 UTC, mattem approved these changes

2022-11-17 07:13 UTC, merged